let DATA=null;
const S={day:1,completed:{},logs:{},customSupp:[],suppChecks:{},extras:[],shopWeek:1};
const $=id=>document.getElementById(id);
function loadState(){try{Object.assign(S,JSON.parse(localStorage.getItem('rtpState')||'{}'))}catch(e){};S.day=Math.min(182,Math.max(1,Number(S.day)||1));}
function save(){localStorage.setItem('rtpState',JSON.stringify(S));}
function train(){return DATA.training[S.day-1]}
function mealFor(day=S.day){const week=Math.floor((day-1)/7);const rw=(week%4)+1;const rd=((day-1)%7)+1;return DATA.recipes.find(r=>r.week===rw&&r.day===rd)}
function phaseFor(w){if(w<=4)return'REBUILD';if(w<=8)return'BASE';if(w<=16)return'BUILD';if(w<=20)return'MARATHON SPECIFIC';if(w<=23)return'PEAK';if(w<=25)return'TAPER';return'RACE';}
function typeLabel(title){title=title.toLowerCase();if(title.includes('long'))return'Long run';if(title.includes('strength')||title.includes('gym'))return'Strength';if(title.includes('rest'))return'Recovery';if(title.includes('race'))return'Race';if(title.includes('key'))return'Quality';if(title.includes('mobility'))return'Mobility';return'Run';}
function render(){const t=train();const done=!!S.completed[S.day];const count=Object.values(S.completed).filter(Boolean).length;const pct=Math.round(count/182*100);$('phaseText').textContent=phaseFor(t.week);$('progressText').textContent=`${count} / 182 COMPLETE`;$('progressBar').style.width=`${count/182*100}%`;$('weekText').textContent=`WEEK ${t.week} • ${t.focus}`;$('dayHeadline').textContent=`Day ${t.day}`;$('percentBadge').textContent=`${pct}%`;$('percentBadge').style.background=`conic-gradient(var(--mint) ${pct*3.6}deg,#2a2243 0deg)`;$('focusChip').textContent=t.focus;$('typeChip').textContent=typeLabel(t.title);$('trainTitle').textContent=t.title;$('trainSummary').textContent=t.summary;$('trainBullets').innerHTML=t.bullets.map(x=>`<li>${escapeHtml(x)}</li>`).join('');const b=$('completeBtn');b.textContent=done?'✓ DAY COMPLETE':'✓ COMPLETE DAY';b.classList.toggle('done',done);const log=S.logs[S.day]||{};$('logTime').value=log.time||'';$('logDistance').value=log.distance||'';$('logHr').value=log.hr||'';$('logRpe').value=log.rpe||'';$('logNotes').value=log.notes||'';const r=mealFor();$('recipeTitle').textContent=r.title;$('recipeRole').textContent=r.role;$('recipeTime').textContent=`${r.minutes} MIN`;renderTodaySupp();renderFuel();renderFood();renderSuppLists();renderShop();$('jumpDay').value=S.day;}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function go(delta){saveLog();S.day=Math.min(182,Math.max(1,S.day+delta));save();render();window.scrollTo({top:0,behavior:'smooth'})}
function saveLog(){S.logs[S.day]={time:$('logTime').value,distance:$('logDistance').value,hr:$('logHr').value,rpe:$('logRpe').value,notes:$('logNotes').value};save();}
function completeDay(){saveLog();S.completed[S.day]=!S.completed[S.day];save();if(S.completed[S.day]){confetti();toast('Day complete — nice work!');render();setTimeout(()=>{if(S.day<182)go(1)},750)}else render();}
function confetti(){const c=$('confetti');c.innerHTML='';const cols=['#ff6f91','#ffd166','#61e7c2','#8f63ff','#ff8066'];for(let i=0;i<44;i++){const e=document.createElement('i');e.style.left=Math.random()*100+'vw';e.style.background=cols[i%cols.length];e.style.animationDelay=(Math.random()*.25)+'s';e.style.transform=`rotate(${Math.random()*180}deg)`;c.appendChild(e)}setTimeout(()=>c.innerHTML='',1500)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')})}
function openRecipe(r=mealFor()){ $('modalRecipeTitle').textContent=r.title;$('modalRecipeMeta').textContent=`${r.role} • ${r.minutes} min • serves 2`;$('modalIngredients').innerHTML=r.ingredients.map(x=>`<li>${escapeHtml(x)}</li>`).join('');$('modalMethod').innerHTML=r.method.map(x=>`<li>${escapeHtml(x)}</li>`).join('');openModal('recipeModal');}
function supplements(){return [...DATA.defaultSupplements,...(S.customSupp||[])]}
function renderTodaySupp(){const day=S.day;const html=['morning','evening'].map(slot=>{const items=supplements().filter(x=>x.slot===slot);if(!items.length)return'';return `<div class="supp-group"><div class="kicker">${slot==='morning'?'☀ MORNING':'☾ EVENING'}</div>${items.map(x=>suppRow(x,day,true)).join('')}</div>`}).join('');$('todaySupplements').innerHTML=html;wireSuppChecks();}
function suppRow(x,day,checkbox){const key=`${day}:${x.id}`;return `<div class="supp-row">${checkbox?`<input class="supp-check" data-suppkey="${key}" type="checkbox" ${S.suppChecks[key]?'checked':''}>`:''}<div class="supp-main"><strong>${escapeHtml(x.name)} — ${escapeHtml(x.dose||'')}</strong><small>${escapeHtml(x.note||'')}</small></div>${x.custom?`<button class="supp-delete" data-del="${x.id}">×</button>`:''}</div>`}
function wireSuppChecks(){document.querySelectorAll('[data-suppkey]').forEach(el=>el.onchange=()=>{S.suppChecks[el.dataset.suppkey]=el.checked;save()})}
function renderSuppLists(){for(const slot of ['morning','evening']){const target=$(slot+'List');const items=supplements().filter(x=>x.slot===slot);target.innerHTML=items.length?items.map(x=>suppRow(x,S.day,false)).join(''):'<p class="muted">Nothing added.</p>'}document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{S.customSupp=S.customSupp.filter(x=>x.id!==b.dataset.del);save();render()})}
function addSupplement(){const name=$('newSuppName').value.trim();if(!name)return;S.customSupp.push({id:'c'+Date.now(),name,dose:$('newSuppDose').value.trim(),slot:$('newSuppSlot').value,note:$('newSuppNote').value.trim(),custom:true});['newSuppName','newSuppDose','newSuppNote'].forEach(id=>$(id).value='');save();closeModals();render();toast('Supplement added')}
function renderFuel(){const title=train().title.toLowerCase();const hits=DATA.fuelRules.filter(r=>r.match.some(m=>title.includes(m)));const card=$('fuelCard');if(!hits.length){card.hidden=true;return}card.hidden=false;$('fuelTitle').textContent=hits.map(h=>h.title).join(' + ');$('fuelText').textContent=hits.map(h=>h.text).join(' ')}
function renderFood(){const rw=(Math.floor((S.day-1)/7)%4)+1;$('foodList').innerHTML=DATA.recipes.filter(r=>r.week===rw).map(r=>`<div class="food-item" data-rw="${r.week}" data-rd="${r.day}"><div class="top"><div><span class="kicker">DAY ${r.day}</span><h3>${escapeHtml(r.title)}</h3><span class="muted">${escapeHtml(r.role)}</span></div><span class="timepill">${r.minutes} MIN</span></div></div>`).join('');document.querySelectorAll('.food-item').forEach(el=>el.onclick=()=>openRecipe(DATA.recipes.find(r=>r.week==el.dataset.rw&&r.day==el.dataset.rd)))}
function renderShop(){const buttons=[1,2,3,4].map(w=>`<button class="${S.shopWeek==w?'active':''}" data-shopw="${w}">Food week ${w}</button>`).join('');$('shopWeeks').innerHTML=buttons;document.querySelectorAll('[data-shopw]').forEach(b=>b.onclick=()=>{S.shopWeek=+b.dataset.shopw;save();renderShop()});const cats=DATA.shopping[String(S.shopWeek)];$('shopList').innerHTML=Object.entries(cats).map(([cat,items])=>`<div class="shop-cat"><h4>${escapeHtml(cat)}</h4>${items.map((x,i)=>`<label class="shop-item"><input type="checkbox"><span>${escapeHtml(x)}</span></label>`).join('')}</div>`).join('');renderExtras();}
function renderExtras(){const list=S.extras||[];$('extrasList').innerHTML=list.length?list.map((x,i)=>`<div class="supp-row"><div class="supp-main"><strong>${escapeHtml(x)}</strong></div><button class="supp-delete" data-exdel="${i}">×</button></div>`).join(''):'<p class="muted">Add milk, eggs, toiletries or anything you always want in the shop.</p>';document.querySelectorAll('[data-exdel]').forEach(b=>b.onclick=()=>{S.extras.splice(+b.dataset.exdel,1);save();renderExtras()})}
function addExtra(){const v=$('extraInput').value.trim();if(!v)return;S.extras.push(v);$('extraInput').value='';save();renderExtras();toast('Added to extras')}
async function copyShop(){const cats=DATA.shopping[String(S.shopWeek)];let txt=`ROAD TO PARIS — FOOD WEEK ${S.shopWeek}\n\n`;for(const [c,items] of Object.entries(cats)){txt+=`[${c}]\n${items.map(x=>'- '+x).join('\n')}\n\n`}if(S.extras.length)txt+=`[OUR EXTRAS / ALWAYS ADD]\n${S.extras.map(x=>'- '+x).join('\n')}\n\n`;txt+='VALUE RULE: compare £/kg, £/L and £/unit; choose sensible cheaper equivalents; use bulk/multibuy only if unit price is lower and excess can be used or frozen.';await navigator.clipboard.writeText(txt);toast('Shopping list copied')}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function setupSwipe(){let x=0,y=0;$('dayCard').addEventListener('touchstart',e=>{x=e.touches[0].clientX;y=e.touches[0].clientY},{passive:true});$('dayCard').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x,dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.3)go(dx<0?1:-1)},{passive:true})}
async function init(){DATA=await fetch('data.json').then(r=>r.json());loadState();render();setupSwipe();$('completeBtn').onclick=completeDay;$('openRecipe').onclick=()=>openRecipe();$('addSuppBtn').onclick=()=>openModal('suppModal');$('saveSuppBtn').onclick=addSupplement;$('settingsBtn').onclick=()=>openModal('settingsModal');$('jumpBtn').onclick=()=>{saveLog();S.day=Math.min(182,Math.max(1,+$('jumpDay').value||1));save();closeModals();render()};$('resetBtn').onclick=()=>{if(confirm('Reset all progress, logs, supplement ticks and extras on this device?')){localStorage.removeItem('rtpState');location.reload()}};$('addExtraBtn').onclick=addExtra;$('copyShopBtn').onclick=copyShop;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModals);document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});document.querySelectorAll('.bottomnav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));['logTime','logDistance','logHr','logRpe','logNotes'].forEach(id=>$(id).addEventListener('change',saveLog));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
init();